namespace:
  name: prod
service:
  port: 7111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP
image:
  repository: shubham16598/techtrends
  tag: v1.0.0
  pullPolicy: Always
replicaCount: 5
resources:
  requests:
    cpu: 350m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi
containerPorts:
  http:
    port: 3111
    protocol: TCP
livenessProbe:
  httpGet:
    path: /healthz
    port: 3111
readinessProbe:
  httpGet:
    path: /healthz
    port: 3111